export const LOAD_PROPERTIES_REQUEST = 'LOAD_PROPERTIES_REQUEST';
export const LOAD_PROPERTIES_SUCCESS = 'LOAD_PROPERTIES_SUCCESS';
export const LOAD_PROPERTIES_FAIL = 'LOAD_PROPERTIES_FAIL';

export const LOAD_FILTEREDPROPERTIES_REQUEST = 'LOAD_FILTEREDPROPERTIES_REQUEST';
export const LOAD_FILTEREDPROPERTIES_SUCCESS = 'LOAD_FILTEREDPROPERTIES_SUCCESS';
export const LOAD_FILTEREDPROPERTIES_FAIL = 'LOAD_FILTEREDPROPERTIES_FAIL';

export const LOAD_PROPERTIESBYCATEGORY_REQUEST = 'LOAD_PROPERTIESBYCATEGORY_REQUEST';
export const LOAD_PROPERTIESBYCATEGORY_SUCCESS = 'LOAD_PROPERTIESBYCATEGORY_SUCCESS';
export const LOAD_PROPERTIESBYCATEGORY_FAIL = 'LOAD_PROPERTIESBYCATEGORY_FAIL';

export const LOAD_PROPERTYTYPES_REQUEST = 'LOAD_PROPERTYTYPES_REQUEST';
export const LOAD_PROPERTYTYPES_SUCCESS = 'LOAD_PROPERTYTYPES_SUCCESS';
export const LOAD_PROPERTYTYPES_FAIL = 'LOAD_PROPERTYTYPES_FAIL';

export const LOAD_PROPERTYSTATUS_REQUEST = 'LOAD_PROPERTYSTATUS_REQUEST';
export const LOAD_PROPERTYSTATUS_SUCCESS = 'LOAD_PROPERTYSTATUS_SUCCESS';
export const LOAD_PROPERTYSTATUS_FAIL = 'LOAD_PROPERTYSTATUS_FAIL';

export const PROPERTYSEARCH_REQUEST = 'PROPERTYSEARCH_REQUEST';
export const PROPERTYSEARCH_SUCCESS = 'PROPERTYSEARCH_SUCCESS';
export const PROPERTYSEARCH_FAIL = 'PROPERTYSEARCH_FAIL';

export const CHECK_CONNECTION = 'CHECK_CONNECTION';
