export const LOAD_PROPERTIES_REQUEST = 'LOAD_PROPERTIES_REQUEST';
export const LOAD_PROPERTIES_SUCCESS = 'LOAD_PROPERTIES_SUCCESS';
export const LOAD_PROPERTIES_FAIL = 'LOAD_PROPERTIES_FAIL';

export const LOAD_FILTERED_PROPERTIES_REQUEST = 'LOAD_FILTERED_PROPERTIES_REQUEST';
export const LOAD_FILTERED_PROPERTIES_SUCCESS = 'LOAD_FILTERED_PROPERTIES_SUCCESS';
export const LOAD_FILTERED_PROPERTIES_FAIL = 'LOAD_FILTERED_PROPERTIES_FAIL';

export const LOAD_PROPERTIES_CATEGORY_REQUEST = 'LOAD_PROPERTIES_CATEGORY_REQUEST';
export const LOAD_PROPERTIES_CATEGORY_SUCCESS = 'LOAD_PROPERTIES_CATEGORY_SUCCESS';
export const LOAD_PROPERTIES_CATEGORY_FAIL = 'LOAD_PROPERTIES_CATEGORY_FAIL';

export const LOAD_PROPERTY_TYPES_REQUEST = 'LOAD_PROPERTY_TYPES_REQUEST';
export const LOAD_PROPERTY_TYPES_SUCCESS = 'LOAD_PROPERTY_TYPES_SUCCESS';
export const LOAD_PROPERTY_TYPES_FAIL = 'LOAD_PROPERTY_TYPES_FAIL';

export const LOAD_PROPERTY_STATUS_REQUEST = 'LOAD_PROPERTY_STATUS_REQUEST';
export const LOAD_PROPERTY_STATUS_SUCCESS = 'LOAD_PROPERTY_STATUS_SUCCESS';
export const LOAD_PROPERTY_STATUS_FAIL = 'LOAD_PROPERTY_STATUS_FAIL';

export const PROPERTY_SEARCH_REQUEST = 'PROPERTY_SEARCH_REQUEST';
export const PROPERTY_SEARCH_SUCCESS = 'PROPERTY_SEARCH_SUCCESS';
export const PROPERTY_SEARCH_FAIL = 'PROPERTY_SEARCH_FAIL';

export const SAVED_SEARCH_REQUEST = 'SAVED_SEARCH_REQUEST';
export const SAVED_SEARCH_SUCCESS = 'SAVED_SEARCH_SUCCESS';
export const SAVED_SEARCH_FAIL = 'SAVED_SEARCH_FAIL';

export const CHECK_CONNECTION = 'CHECK_CONNECTION';

export const SEARCH_CHANGE = 'SEARCH_CHANGE';
