export const LOAD_PROPERTIES_REQUEST = 'LOAD_PROPERTIES_REQUEST';
export const LOAD_PROPERTIES_SUCCESS = 'LOAD_PROPERTIES_SUCCESS';
export const LOAD_PROPERTIES_FAIL = 'LOAD_PROPERTIES_FAIL';

export const LOAD_PROPERTIESBYCATEGORY_REQUEST = 'LOAD_PROPERTIESBYCATEGORY_REQUEST';
export const LOAD_PROPERTIESBYCATEGORY_SUCCESS = 'LOAD_PROPERTIESBYCATEGORY_SUCCESS';
export const LOAD_PROPERTIESBYCATEGORY_FAIL = 'LOAD_PROPERTIESBYCATEGORY_FAIL';

export const CHECK_CONNECTION = 'CHECK_CONNECTION';