import * as config from '../constants/config';

export default {
  common: {
    loading: false,
    error: false,
    success: false,
  },
  search: config.search,
  PostProperty: {
  	propertyFor: '33',
  	region: '',
  	branch: '',
  	district: '',
  	address: '',
  	unitFloor: '',
  	locationOnMap: '',
  	propertyTitle: '',
  	propertyDescription: '',
  	ownerName: '',
  	ownerPhone: '',
  	agency: '',
  	agent: '',
  	rentPerMonth: '',
  	dateAvailable: 'Select Date',
  	propertyType: '',
  	rooms: '1',
  	bathrooms: '1',
  	meterSq: '',
  	yearBuild: '',
  	viewR: '',
  	featuresR: '',
  	commonFacilitiesR: '',
  	additionalFeaturesR: '',
    screen_1: false,
    screen_2: false,
    screen_3: false,
    screen_4: false,
    screen_5: false,
    screen_6: false,
  }
};